### ISSUE TITLE
Expansions used in games not clearly listed

### ISSUE THREAD

**Issue by MasterNayru** [crustymonkey/playeraid_modules#15]
Before I start, this site is absolutely unreal. Really loving this!

I have been working on something similar for my own use (not really made for public consumption, just things to make my own setup and games for my own group a bit smoother) and would be very interested in contributing player aids that I have been putting together. 

One thing I am noticing, though, is when I have a player aid that says "with expansions", it can be helpful to know exactly which expansions the guide assumes are in use. For example, with the Scythe one you enabled today, I assume that it is written to use at least the Invaders from Afar expansion as it includes information about the Togawa Shogunate and Clan Albion, but I wouldn't know whether the guide assumes I also have the Wind Gambit expansion without reading through the whole thing.

I noticed this with the Trickerion player aid where I saw "with expansions" and thought "Thank goodness I paid an arm and a leg for all of them so I am covered"

I would think it would at least be nice to have a top level key saying what expansions exactly are assumed to be used in the setup, just to avoid having the player aid end up with a bunch of super verbose "If you have this ... but if not ..." stuff in it.

**Comment by crustymonkey** [comment]
Yeah, that's a reasonable call.  Up to this point, it's been pretty free-form in terms of expansions.  I'll add a field in the module config to list expansions and surface that on the main page and in the module itself.  Good idea.

**Comment by crustymonkey** [comment]
I've made some updates to make the expansions more clearly, and in a more standard way, displayed on the main page and in the aid itself.
